name: Nexus Hub Program
on:
  schedule:
    # Run every 5 minutes (the '*/5' means every 5th minute)
    - cron: '*/5 * * * *'
  workflow_dispatch: # This allows you to press a "Run" button in GitHub!

jobs:
  run-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install requests

      - name: Run Hub Modules
        # You can add as many modules here as you want
        run: |
          python Nexus_System/modules/steam_price_tracker.py
          python "Nexus_System/modules/Southern Bot Check.py"
        env:
           TRAIN_WEBHOOK_URL: ${{ secrets.TRAIN_WEBHOOK_URL }}
           GAMING_PRICE_WEBHOOK_URL: ${{ secrets.GAMING_PRICE_WEBHOOK_URL }}
